---
abstract: '(Perl) fdupes variant, where duplicates are searched from a central (pivotal) directory'
author:
  - 'Clipland (clipland@cpan.org)'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132830'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-fdupes-pivotal
no_index:
  directory:
    - t
    - inc
requires:
  Digest::MD5::File: 0
  File::Basename: 0
  File::Find: 0
  File::Spec: 0
resources: {}
version: 0.02
